/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class HostSession {

}

export declare class OwnerLease {

}

export declare class PtySession {
  constructor()
  start(options: PtyStartOptions, onChunk?: ((error: Error | null, chunk: string) => void) | undefined | null): Promise<PtyRunResult>
  write(data: string): void
  resize(cols: number, rows: number): void
  kill(): void
}

/**
 * Opaque ownership lease for the exact Postgres process spawned by Atomic.
 *
 * Keeping the native child object prevents PID reuse until the process has
 * been observed and reaped. Dropping/releasing the lease deliberately does
 * not terminate the server, preserving abrupt-exit persistence.
 */
export declare class RetainedPostgres {
  get pid(): number | null
  interruptAndWait(timeoutMs: number): Promise<RetainedPostgresWaitResult>
  wait(timeoutMs: number): Promise<RetainedPostgresWaitResult>
  /** Relinquish ownership without signaling or waiting for Postgres. */
  release(): void
}

export declare class RunnerLease {

}

/**
 * N-API wrapper around the root-scoped Rust control plane. The host marker is
 * intentionally held by the wrapper while the cloneable core stores only a
 * weak reference to it.
 */
export declare class SubagentControl {
  constructor(parentPath: string)
  get parentPath(): string
  registerAgent(name: string): void
  admitChildSession(spec: NativeChildSpec, parent: NativeParentContext): NativeAdmissionResult
  listChildren(): Array<ChildIdentity>
  publishChildStatus(path: string, status: AgentStatus): void
  subscribeChildStatus(path: string, callback: (status: AgentStatus) => void): void
  subscribeChildStatusWithCause(path: string, callback: (update: NativeStatusUpdate) => void): void
  tryAcquireExecutionGuard(): NativeExecutionGuardResult
  releaseExecutionGuard(token: number): boolean
  beginChildAttempt(path: string): NativeExecutionGuardResult
  finishChildAttempt(token: number, status: AgentStatus): void
  terminateChildAttempt(token: number, cause: TerminationCause): Promise<NativeTerminationResult>
}
export type NapiSubagentControl = SubagentControl

export declare class SubscriptionLease {

}

export declare class TaskLease {

}

/** A single serialized native actor is shared by all instances in this environment. */
export declare class TaskSupervisor {
  constructor()
  /** Trusted-host seam only. Host authorization must run before admission. */
  bindHostSession(scope: OwnerScope): HostSession
openTaskOwner(host: HostSession, scope: OwnerScope): {ok:true,value:OwnerLease}|{ok:false,error:TaskFailure}
startAgentTask(owner: OwnerLease, intent: AgentIntent, operation: string): {ok:true,value:TaskLease}|{ok:false,error:TaskFailure}
/** Claim once after host dispatch setup; operation replay never grants a second runner. */
claimTaskRunner(task: TaskLease): {ok:true,value:RunnerLease}|{ok:false,error:TaskFailure}
taskReference(task: TaskLease): {ok:true,value:NativeTaskRef}|{ok:false,error:TaskFailure}
lookupTask(owner: OwnerLease, taskId: string): {ok:true,value:TaskLease}|{ok:false,error:TaskFailure}
/**
 * Registers the observation before returning. Await observeTaskWait separately.
 * Accepts the host-resolved numeric budget without u32 narrowing; omission arms no timer.
 */
waitForTask(task: TaskLease, budgetMs?: number | undefined | null, designation?: HostSession | undefined | null): {ok:true,value:WaitLease}|{ok:false,error:TaskFailure}
foregroundTask(task: TaskLease, host: HostSession, budgetMs?: number | undefined | null): {ok:true,value:WaitLease}|{ok:false,error:TaskFailure}
observeTaskWait(wait: WaitLease): Promise<{ok:true,value:WaitOutcome}|{ok:false,error:TaskFailure}>
yieldTaskWait(wait: WaitLease, reason: YieldReason): {ok:true,value:WaitOutcome}|{ok:false,error:TaskFailure}
disposeTaskWait(wait: WaitLease): {ok:true,value:undefined}|{ok:false,error:TaskFailure}
cancelTask(task: TaskLease, cause: CancelCause): {ok:true,value:CancelReceipt}|{ok:false,error:TaskFailure}
/** Seals synchronously, then awaits independent runner cleanup acknowledgements. */
closeTaskOwner(owner: OwnerLease, cause: OwnerCloseCause): Promise<{ok:true,value:OwnerCloseReceipt}|{ok:false,error:TaskFailure}>
reportTaskActivity(runner: RunnerLease, report: ActivityReport): {ok:true,value:ReportReceipt}|{ok:false,error:TaskFailure}
reportTaskOutcome(runner: RunnerLease, report: OutcomeReport): {ok:true,value:SettlementReceipt}|{ok:false,error:TaskFailure}
/** Private trusted-runner support, not a model/facade domain door. Outcome is not cleanup. */
acknowledgeTaskCleanup(runner: RunnerLease, cleanup: Cleanup): {ok:true,value:Cleanup}|{ok:false,error:TaskFailure}
/**
 * The callback wakes a drain. The host must also keep one bounded reconciliation poll
 * until disposal/owner closure: an oversized evicted event has no authentic wake payload.
 */
watchOwnerTasks(owner: OwnerLease, callback: (event: NativeEvent) => void, cursor?: Cursor | undefined | null): {ok:true,value:NativeTaskSubscription}|{ok:false,error:TaskFailure}
drainOwnerTasks(lease: SubscriptionLease): {ok:true,value:SubscriptionDrain}|{ok:false,error:TaskFailure}
disposeSubscription(lease: SubscriptionLease): void
}
export type NapiTaskSupervisor = TaskSupervisor

export declare class WaitLease {
  get waitId(): string
}

export type ActivityChange =
  | { kind: 'action', tool: string, text: string }
  | { kind: 'metrics', elapsedMs?: number, toolCount?: number, tokenCount?: number }
  | { kind: 'output', offset: string, bytesBase64: string }
  | { kind: 'attention-set', attention: Attention }
  | { kind: 'attention-clear', requestId: string }

export interface ActivityReport {
  reportId: string
  change: ActivityChange
}

export type AdmissionRefusalKind =  'depthExceeded'|
'capacityExhausted'|
'dispatchGuardBusy'|
'invalidCwd'|
'unknownAgent'|
'terminalChild';

export interface AgentIntent {
  kind: AgentTaskKind
  agent: string
  task: string
  description?: string
  cwd?: string
  parentTaskId?: string
}

/** The only statuses emitted by a child status watch. */
export type AgentStatus =  'pending'|
'running'|
'ok'|
'error'|
'interrupted'|
'continued';

export type AgentTaskKind =  'agent';

export type Attention =
  | { kind: 'none' }
  | { kind: 'input-needed', requestId: string, prompt: string, route: PromptRoute }
  | { kind: 'no-recent-activity', lastActivityAt?: string }

export interface BlockRange {
  /** 1-indexed inclusive first line of the resolved block. */
  startLine: number
  /** 1-indexed inclusive last line of the resolved block. */
  endLine: number
}

/**
 * Resolve the block beginning on `options.line`. Returns `None` when the
 * language is unrecognized, the line is out of range / blank, no node begins
 * there, or the resolved subtree contains a syntax error.
 */
export declare function blockRangeAt(options: BlockRangeOptions): BlockRange | null

export interface BlockRangeOptions {
  /** Source code to inspect. */
  code: string
  /** File path used to infer the language by extension. */
  path: string
  /** 1-indexed source line the block must begin on. */
  line: number
}

export type CancelCause =  'user'|
'owner-close'|
'execution-timeout'|
'output-limit'|
'parent-handoff'|
'shutdown';

export interface CancelReceipt {
  taskId: string
  decision: string
  execution: Execution
  cleanup: Cleanup
}

/** Persistent identity information returned by the registry. */
export interface ChildIdentity {
  path: string
  parentPath: string
  taskName: string
  depth: number
  status: AgentStatus
  cause?: TerminationCause
  loaded: boolean
}

export type Cleanup =
  | { kind: 'active' }
  | { kind: 'draining' }
  | { kind: 'reaped' }
  | { kind: 'failed', resources: Array<ResourceFailure> }

/** A context line (before or after a match). */
export interface ContextLine {
  /** 1-indexed line number in the source file. */
  lineNumber: number
  /** Raw line content (trimmed line ending). */
  line: string
}

export interface CurrentAction {
  tool: string
  text: string
}

export interface Cursor {
  generation: string
  sequence: string
}

export type Execution =
  | { kind: 'queued' }
  | { kind: 'running' }
  | { kind: 'cancelling', cause: CancelCause }
  | { kind: 'settled', result: TaskResult }

/** Resolved filesystem entry kind for glob filters and match metadata. */
export declare enum FileType {
  /** Regular file. */
  File = 1,
  /** Directory. */
  Dir = 2,
  /** Symbolic link. */
  Symlink = 3
}

/**
 * Find filesystem entries matching a glob pattern.
 *
 * Resolves the search root, scans entries, applies glob and optional file-type
 * filters, and optionally streams each accepted match through `on_match`.
 *
 * If `sortByMtime` is enabled with a finite `maxResults`, uncached scans keep
 * only the current top results while traversing instead of collecting the full
 * tree.
 *
 * # Errors
 * Returns an error when the search path cannot be resolved, the path is not a
 * directory, the glob pattern is invalid, or cancellation/timeout is
 * triggered.
 */
export declare function glob(options: GlobOptions, onMatch?: ((error: Error | null, match: GlobMatch) => void) | undefined | null): Promise<GlobResult>

/** A single filesystem entry from a directory scan. */
export interface GlobMatch {
  /** Relative path from the search root, using forward slashes. */
  path: string
  /** Resolved filesystem type for the match. */
  fileType: FileType
  /**
   * Modification time in milliseconds since Unix epoch (from
   * `symlink_metadata`).
   */
  mtime?: number
  /** File size in bytes for regular files. */
  size?: number
}

/** Input options for `glob`, including traversal, filtering, and cancellation. */
export interface GlobOptions {
  /** Glob pattern to match (e.g., "*.ts"). */
  pattern: string
  /** Directory to search. */
  path: string
  /**
   * Filter by file type: "file", "dir", or "symlink". Symlinks are
   * matched for file/dir filters based on their target type.
   */
  fileType?: FileType
  /** Match simple patterns recursively by default (`*.ts` -> recursive). */
  recursive?: boolean
  /** Include hidden files (default: false). */
  hidden?: boolean
  /** Maximum number of results to return. */
  maxResults?: number
  /** Respect .gitignore files (default: true). */
  gitignore?: boolean
  /** Enable shared filesystem scan cache (default: false). */
  cache?: boolean
  /** Sort results by mtime (most recent first) before applying limit. */
  sortByMtime?: boolean
  /**
   * Include `node_modules` entries when the pattern does not explicitly
   * mention them.
   */
  includeNodeModules?: boolean
  /** Abort signal for cancelling the operation. */
  signal?: unknown
  /** Timeout in milliseconds for the operation. */
  timeoutMs?: number
}

/** Result payload returned by a glob operation. */
export interface GlobResult {
  /** Matched filesystem entries. */
  matches: Array<GlobMatch>
  /** Number of returned matches (`matches.len()`), clamped to `u32::MAX`. */
  totalMatches: number
}

/**
 * Search files for a regex pattern.
 *
 * # Arguments
 * - `options`: Pattern, path, filters, and output mode.
 * - `on_match`: Optional callback invoked per match/result.
 *
 * # Returns
 * Aggregated results across matching files.
 */
export declare function grep(options: GrepOptions, onMatch?: ((error: Error | null, match: GrepMatch) => void) | undefined | null): Promise<GrepResult>

/** A single match in a grep result. */
export interface GrepMatch {
  /** File path for the match (relative for directory searches). */
  path: string
  /** 1-indexed line number (0 for count-only entries). */
  lineNumber: number
  /** The matched line content (empty for count-only entries). */
  line: string
  /** Context lines before the match. */
  contextBefore?: Array<ContextLine>
  /** Context lines after the match. */
  contextAfter?: Array<ContextLine>
  /** Whether the line was truncated. */
  truncated?: boolean
  /** Per-file match count (count mode only). */
  matchCount?: number
}

/** Options for searching files on disk. */
export interface GrepOptions {
  /** Regex pattern to search for. */
  pattern: string
  /** Directory or file to search. */
  path: string
  /** Workspace/root used to evaluate path-qualified glob filters for explicit files. */
  cwd?: string
  /** Glob filter for filenames (e.g., "*.ts"). */
  glob?: string
  /** Filter by file type (e.g., "js", "py", "rust"). */
  type?: string
  /** Case-insensitive search. */
  ignoreCase?: boolean
  /** Enable multiline matching. */
  multiline?: boolean
  /** Include hidden files (default: true). */
  hidden?: boolean
  /** Respect .gitignore files (default: true). */
  gitignore?: boolean
  /** Enable shared filesystem scan cache (default: false). */
  cache?: boolean
  /** Maximum number of matches to return. */
  maxCount?: number
  /** Skip first N matches. */
  offset?: number
  /** Lines of context before matches. */
  contextBefore?: number
  /** Lines of context after matches. */
  contextAfter?: number
  /** Lines of context before/after matches (legacy). */
  context?: number
  /** Truncate lines longer than this (characters). */
  maxColumns?: number
  /** Output mode (content, filesWithMatches, or count). */
  mode?: GrepOutputMode
  /**
   * Maximum matches collected per file (content mode). Keeps one hot file
   * from exhausting the global `max_count` budget before other files are
   * reached.
   */
  maxCountPerFile?: number
  /** Abort signal for cancelling the operation. */
  signal?: unknown
  /** Timeout in milliseconds for the operation. */
  timeoutMs?: number
}

/** Output mode for [`search`] and [`grep`] (string values match JS callers). */
export type GrepOutputMode = /** Emit matched lines (and optional context lines). */
'content'|
/** Emit per-file or total counts instead of line content. */
'count'|
/** Emit one row per file that matched| without line content. */
'filesWithMatches';

/** Result of searching files. */
export interface GrepResult {
  /** Matches or per-file counts, depending on output mode. */
  matches: Array<GrepMatch>
  /**
   * Total matches across all files, or matched file count in filesWithMatches
   * mode.
   */
  totalMatches: number
  /** Number of files with at least one match. */
  filesWithMatches: number
  /** Number of files searched. */
  filesSearched: number
  /** Whether the limit/offset stopped the search early. */
  limitReached?: boolean
  /** Number of files skipped because they exceed the size limit. */
  skippedOversized?: number
}

/**
 * Quick check if content matches a pattern.
 *
 * # Arguments
 * - `content`: `Uint8Array`/`Buffer` (zero-copy) or `string` (UTF-8).
 * - `pattern`: `Uint8Array`/`Buffer` (zero-copy) or `string` (UTF-8).
 * - `ignore_case`: Case-insensitive matching.
 * - `multiline`: Enable multiline regex mode.
 *
 * # Returns
 * True if any match exists; false on no match.
 */
export declare function hasMatch(content: string | Uint8Array, pattern: string | Uint8Array, ignoreCase?: boolean | undefined | null, multiline?: boolean | undefined | null): boolean

export type HostObservation =
  | { kind: 'foreground', waitId: string }
  | { kind: 'background', reason: string }
  | { kind: 'none', reason: string }

/**
 * Invalidate the filesystem scan cache.
 *
 * When called with a path, removes entries for roots containing that path.
 * When called without a path, clears the entire cache.
 *
 * Intended to be called after agent file mutations (write, edit, rename,
 * delete).
 */
export declare function invalidateFsScanCache(path?: string | undefined | null): void

/** A single match in the content. */
export interface Match {
  /** 1-indexed line number. */
  lineNumber: number
  /** The matched line content. */
  line: string
  /** Context lines before the match. */
  contextBefore?: Array<ContextLine>
  /** Context lines after the match. */
  contextAfter?: Array<ContextLine>
  /** Whether the line was truncated. */
  truncated?: boolean
}

export interface NativeAdmissionRefusal {
  kind: AdmissionRefusalKind
  reason: string
  maxDepth?: number
}

export interface NativeAdmissionResult {
  child?: ChildIdentity
  refusal?: NativeAdmissionRefusal
}

export interface NativeChildSpec {
  taskName: string
  agentName?: string
  cwd?: string
}

export interface NativeEvent {
  schemaVersion: number
  cursor: Cursor
  ownerId: string
  taskId?: string
  payload: TaskEvent
}

export interface NativeExecutionGuardResult {
  token?: number
  refusal?: NativeAdmissionRefusal
}

export interface NativeParentContext {
  path: string
  depth: number
}

export interface NativeStatusUpdate {
  status: AgentStatus
  cause?: TerminationCause
}

export interface NativeTaskRef {
  ownerId: string
  taskId: string
  attemptId: string
  generation: string
}

export interface NativeTaskSubscription {
  lease: SubscriptionLease
  snapshot: OwnerSnapshot
  cursor: Cursor
}

export interface NativeTerminationResult {
  cause: TerminationCause
  forced: boolean
  graceMs: number
}

export interface OmittedRange {
  start: string
  end: string
}

export interface OutcomeReport {
  reportId: string
  result: TaskResult
}

export interface OutputRef {
  ownerId: string
  taskId: string
  artifactId: string
  byteCount: string
  omittedRanges: Array<OmittedRange>
}

export type OwnerCloseCause =  'session-close'|
'stage-close'|
'app-shutdown';

export interface OwnerCloseReceipt {
  ownerId: string
  state: string
  tasks: Array<CancelReceipt>
}

export type OwnerScope =
  | { kind: 'session', sessionId: string }
  | { kind: 'workflow-stage', sessionId: string, runId: string, stageId: string, stageAttemptId: string }

export interface OwnerSnapshot {
  ownerId: string
  scope: OwnerScope
  generation: string
  state: string
  tasks: Array<TaskRecord>
  cursor: Cursor
}

export interface PromptRoute {
  sessionId: string
  promptId: string
  stageAttemptId?: string
}

export interface PtyRunResult {
  exitCode?: number
  cancelled: boolean
  timedOut: boolean
}

export interface PtyStartOptions {
  command: string
  cwd?: string
  env?: Record<string, string>
  timeoutMs?: number
  signal?: unknown
  cols?: number
  rows?: number
  shell?: string
  shellArgs?: Array<string>
  commandTransport?: string
  closeStdinAfterCommand?: boolean
}

export interface ReportReceipt {
  reportId: string
  cursor: Cursor
  disposition: string
}

export interface ResourceFailure {
  resource: string
  code: string
  message: string
}

export interface RetainedPostgresSpawnOptions {
  executable: string
  args: Array<string>
  cwd: string
  logFile: string
  env?: Record<string, string>
  uid?: number
  gid?: number
}

export interface RetainedPostgresWaitResult {
  exited: boolean
  signaled: boolean
}

/**
 * Search content for a pattern (one-shot, compiles pattern each time).
 * For repeated searches with the same pattern, use [`grep`] with file filters.
 *
 * # Arguments
 * - `content`: `Uint8Array`/`Buffer` (zero-copy) or `string` (UTF-8).
 * - `options`: Regex settings, context, and output mode.
 *
 * # Returns
 * Match list plus counts/limit status; errors are surfaced in `error`.
 */
export declare function search(content: string | Uint8Array, options: SearchOptions): SearchResult

/** Options for searching file content. */
export interface SearchOptions {
  /** Regex pattern to search for. */
  pattern: string
  /** Case-insensitive search. */
  ignoreCase?: boolean
  /** Enable multiline matching. */
  multiline?: boolean
  /** Maximum number of matches to return. */
  maxCount?: number
  /** Skip first N matches. */
  offset?: number
  /** Lines of context before matches. */
  contextBefore?: number
  /** Lines of context after matches. */
  contextAfter?: number
  /** Lines of context before/after matches (legacy). */
  context?: number
  /** Truncate lines longer than this (characters). */
  maxColumns?: number
  /** Output mode (content or count). */
  mode?: GrepOutputMode
}

/** Result of searching content. */
export interface SearchResult {
  /** All matches found. */
  matches: Array<Match>
  /** Total number of matches (may exceed `matches.len()` due to offset/limit). */
  matchCount: number
  /** Whether the limit was reached. */
  limitReached: boolean
  /** Error message, if any. */
  error?: string
}

export interface SettlementReceipt {
  taskId: string
  cursor: Cursor
  result: TaskResult
  completionId: string
}

export declare function spawnRetainedPostgres(options: RetainedPostgresSpawnOptions): RetainedPostgres

export interface SubscriptionDrain {
  reset: boolean
  snapshot?: OwnerSnapshot
  cursor: Cursor
  events: Array<NativeEvent>
  failed: boolean
}

export type TaskEvent =
  | { kind: 'task-admitted', task: TaskRecord }
  | { kind: 'task-started', ref: NativeTaskRef }
  | { kind: 'wait-yielded', ref: NativeTaskRef, waitId: string, reason: YieldReason }
  | { kind: 'wait-started', ref: NativeTaskRef, waitId: string, observer: string }
  | { kind: 'host-observation-changed', ref: NativeTaskRef, observation: HostObservation }
  | { kind: 'task-activity', ref: NativeTaskRef, activity: ActivityReport }
  | { kind: 'task-cancelling', ref: NativeTaskRef, cause: CancelCause }
  | { kind: 'task-settled', ref: NativeTaskRef, result: TaskResult, completionId: string }
  | { kind: 'cleanup-changed', ref: NativeTaskRef, cleanup: Cleanup }
  | { kind: 'owner-closing' }
  | { kind: 'owner-closed' }

export interface TaskFailure {
  code: string
  message: string
}

export interface TaskMetrics {
  elapsedMs?: number
  toolCount?: number
  tokenCount?: number
}

export interface TaskRecord {
  ref: NativeTaskRef
  launchOperationId: string
  parentTaskId?: string
  launchGroupId?: string
  launchOrdinal: number
  kind: string
  title: string
  agentName?: string
  execution: Execution
  observation: HostObservation
  attention: Attention
  cleanup: Cleanup
  currentAction?: CurrentAction
  metrics?: TaskMetrics
  output: OutputRef
}

/** Terminal numeric exit codes retain JavaScript number values without i32 narrowing. */
export type TaskResult =
  | { kind: 'completed', output: OutputRef, exitCode?: number }
  | { kind: 'failed', code: string, message: string, output?: OutputRef, exitCode?: number }
  | { kind: 'cancelled', cause: CancelCause, output?: OutputRef }

/**
 * Explicit termination causes. Timer/idle/wall-clock causes are intentionally
 * absent, making timer-driven termination unrepresentable.
 */
export type TerminationCause =  'abort'|
'interrupt'|
'fail-fast-skip'|
'parent-shutdown';

export type WaitOutcome =
  | { kind: 'settled', taskId: string, result: TaskResult }
  | { kind: 'yielded', taskId: string, waitId: string, reason: YieldReason }

export type YieldReason =  'explicit'|
'default-background'|
'elapsed'|
'intercom-coordination'|
'input-needed';
