import { reviewDecisionSchema } from "./goal-schemas.js";

// Keep this model list identical to Ralph's orchestrator while preserving a
// locally contained Goal configuration.
export const orchestratorModelConfig = {
    model: "openai-codex/gpt-6-astra:medium",
    fallbackModels: [
      "github-copilot/gpt-6-astra:medium",
      "openai/gpt-6-astra:medium",
      "anthropic/claude-fable-5-1:medium",
      "github-copilot/claude-fable-5-1:medium",
      "anthropic/claude-opus-5:high",
      "github-copilot/claude-opus-5:high",
      "openai-codex/gpt-5.6-sol:high",
      "github-copilot/gpt-5.6-sol:high",
      "openai/gpt-5.6-sol:high",
      "anthropic/claude-fable-5:medium",
      "github-copilot/claude-fable-5:medium",
      "kimi-coding/k3:max",
      "moonshotai/kimi-k3:max",
      "moonshotai-cn/kimi-k3:max",
      "openai-codex/gpt-5.5:xhigh",
      "github-copilot/gpt-5.5:xhigh",
      "openai/gpt-5.5:xhigh",
      "anthropic/claude-opus-4-8:high",
      "github-copilot/claude-opus-4.8:high",
      "xai/grok-4.6:xhigh",
      "github-copilot/grok-4.6:xhigh",
      "zai/glm-5.3:high",
      "zai-coding-cn/glm-5.3:high",
      "zai/glm-5.3-flash:high",
      "zai-coding-cn/glm-5.3-flash:high",
      "baseten/zai-org/GLM-5.3:high",
      "baseten/zai-org/GLM-5.3-Flash:high",
      "openrouter/openai/gpt-6-astra:medium",
      "openrouter/anthropic/claude-fable-5-1:medium",
      "openrouter/anthropic/claude-opus-5:high",
      "openrouter/openai/gpt-5.6-sol:high",
      "openrouter/anthropic/claude-fable-5:medium",
      "openrouter/moonshotai/kimi-k3:max",
      "openrouter/sakana/fugu-ultra:high",
      "openrouter/openai/gpt-5.5:xhigh",
      "openrouter/anthropic/claude-opus-4-8:high",
      "openrouter/x-ai/grok-4.6:xhigh",
      "openrouter/z-ai/glm-5.3:high",
      "openrouter/z-ai/glm-5.3-flash:high",
    ],
    excludedTools: ["ask_user_question"],
};

// Keep Goal's reviewer configuration independent so GPT-5.6 precedes Kimi K3
// within both the leading direct-provider group and the OpenRouter group.
export const reviewerModelConfig = {
    model: "openai-codex/gpt-6-astra:high",
    fallbackModels: [
      "github-copilot/gpt-6-astra:high",
      "openai/gpt-6-astra:high",
      "anthropic/claude-fable-5-1:high",
      "github-copilot/claude-fable-5-1:high",
      "anthropic/claude-opus-5:high",
      "github-copilot/claude-opus-5:high",
      "anthropic/claude-fable-5:high",
      "github-copilot/claude-fable-5:high",
      "openai-codex/gpt-5.6-sol:high",
      "github-copilot/gpt-5.6-sol:high",
      "openai/gpt-5.6-sol:high",
      "kimi-coding/k3:max",
      "moonshotai/kimi-k3:max",
      "moonshotai-cn/kimi-k3:max",
      "openai-codex/gpt-5.5:xhigh",
      "github-copilot/gpt-5.5:xhigh",
      "openai/gpt-5.5:xhigh",
      "anthropic/claude-opus-4-8:high",
      "github-copilot/claude-opus-4.8:high",
      "xai/grok-4.6:xhigh",
      "github-copilot/grok-4.6:xhigh",
      "zai/glm-5.3:high",
      "zai-coding-cn/glm-5.3:high",
      "zai/glm-5.3-flash:high",
      "zai-coding-cn/glm-5.3-flash:high",
      "baseten/zai-org/GLM-5.3:high",
      "baseten/zai-org/GLM-5.3-Flash:high",
      "openrouter/openai/gpt-6-astra:high",
      "openrouter/anthropic/claude-fable-5-1:high",
      "openrouter/anthropic/claude-opus-5:high",
      "openrouter/anthropic/claude-fable-5:high",
      "openrouter/openai/gpt-5.6-sol:high",
      "openrouter/moonshotai/kimi-k3:max",
      "openrouter/sakana/fugu-ultra:high",
      "openrouter/openai/gpt-5.5:xhigh",
      "openrouter/anthropic/claude-opus-4-8:high",
      "openrouter/x-ai/grok-4.6:xhigh",
      "openrouter/z-ai/glm-5.3:high",
      "openrouter/z-ai/glm-5.3-flash:high",
    ],
    excludedTools: ["ask_user_question"],
    schema: reviewDecisionSchema,
};
